/**
 * Config Types (Browser-safe)
 *
 * Pure type definitions for configuration.
 * Re-exports from @craft-agent/core for compatibility.
 */

// Re-export all config types from core (single source of truth)
export type {
  Workspace,
  McpAuthType,
  AuthType,
  OAuthCredentials,
} from '@craft-agent/core/types';
import type { SensitiveFindingType, SensitiveSeverity } from '../agent/guards/sensitive-context/types.ts';

/** App-level network proxy configuration. */
export interface NetworkProxySettings {
  enabled: boolean;
  httpProxy?: string;
  httpsProxy?: string;
  noProxy?: string;
}

export type SensitiveContextProtectionMode = 'personal' | 'balanced' | 'strict';
export type SensitiveContextProtectionAction = 'allow' | 'redact' | 'block' | 'prompt';

export interface SensitiveFeatureToggle {
  enabled: boolean;
}

/** App-level Sensitive Context Protection configuration. */
export interface SensitiveContextProtectionSettings {
  enabled: boolean;
  /** Protect .env, private keys, cloud credentials, and similar files before tools run. */
  sensitiveFiles: {
    enabled: boolean;
    action: Extract<SensitiveContextProtectionAction, 'prompt' | 'block'>;
  };
  /** Best-effort redaction for tool results before they enter model context. */
  outputRedaction: SensitiveFeatureToggle;
  /** Structured data field-level redaction. Rules are generated by conversation, not edited here. */
  fieldRedaction: SensitiveFeatureToggle;
  /** Confirm before content is sent to external tools or services. */
  egressConfirmation: SensitiveFeatureToggle;
  audit: {
    enabled: boolean;
    storeRawValues: false;
  };

  /**
   * Legacy/internal policy fields. These are kept optional for migration and
   * guard compatibility; the personal UI no longer exposes safety levels.
   */
  mode?: SensitiveContextProtectionMode;
  credentialFiles: {
    enabled: boolean;
    action: SensitiveContextProtectionAction;
  };
  secrets: {
    enabled: boolean;
    action: SensitiveContextProtectionAction;
  };
  privateKeys: {
    enabled: boolean;
    action: SensitiveContextProtectionAction;
  };
  pii: {
    enabled: boolean;
    action: SensitiveContextProtectionAction;
  };
  lowConfidence: {
    action: SensitiveContextProtectionAction;
  };
  customPatterns: Array<{
    name: string;
    pattern: string;
    type: SensitiveFindingType;
    severity: SensitiveSeverity;
    action: SensitiveContextProtectionAction;
  }>;
}
